[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "django_herobiz_dental"
version = "3.3.2"
description = "my demiansoft templates"
authors = [{name = "Hyungjin Kim", email = "hj3415@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
    "Django >= 4.2.11",
    "libsass>=0.23.0",
    "django-analyticsds >= 0.3.1",
    "django-calendards >= 0.4.0",
    "django-modalds >= 0.1.0",
    "django-utilsds >= 0.6.0",
    "django-mdeditor >= 0.1.20",
    "django-hitcount >= 1.3.5",
    "django-taggit >= 5.0.1",
    "django-markdownify >= 0.9.3",
    "django-light >= 0.1.0",
    "pillow >= 10.3.0",
]

[project.urls]
Home = "https://www.demiansoft.com"

[tool.flit.sdist]
# include = ["analyticsds/","calendards/","popupds/"]
exclude = [
    "_data/",
    "_static/",
    "_mytester/",
    "media/",
    "db.sqlite3",
    "manage.py",
]