[tool.poetry]
name = "imgcv"
version = "0.9.0"
description = "Image Processing Library"
authors = ["Preet Sojitra"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.4"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
myst-nb = {version = "^1.0.0", python = "^3.9"}
sphinx-autoapi = "^3.0.0"
sphinx-rtd-theme = "^2.0.0"
python-semantic-release = "^9.3.1"

[tool.semantic_release]
version_toml = ["pyproject.toml:tool.poetry.version",]          # The version variable to update
branch = "main"                                                 # branch to make release from
changelog_file = "CHANGELOG.md"                                 # changelog file to update
build_command = "pip install poetry && poetry build"            # command to build the package

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
