[dependencies]
common-daft-config = {path = "../common-daft-config", default-features = false}
common-error = {path = "../common-error", default-features = false}
common-io-config = {path = "../common-io-config", default-features = false}
common-py-serde = {path = "../common-py-serde", default-features = false}
common-treenode = {path = "../common-treenode", default-features = false}
daft-core = {path = "../daft-core", default-features = false}
daft-dsl = {path = "../daft-dsl", default-features = false}
daft-scan = {path = "../daft-scan", default-features = false}
daft-table = {path = "../daft-table", default-features = false}
indexmap = "2.1.0"
itertools = "0.11"
serde_json = "1.0.116"

[features]
default = ["python"]
python = ["dep:pyo3", "common-error/python", "common-io-config/python", "common-daft-config/python", "daft-core/python", "daft-dsl/python", "daft-table/python"]

[package]
edition = "2021"
name = "daft-plan"
version = "0.2.26"

[dependencies.snafu]
version = "0.7.4"
features = [ "futures",]

[dependencies.arrow2]
git = "https://github.com/Eventual-Inc/arrow2"
package = "arrow2"
rev = "4a893a1d05e643273c984c6ccc21f4904d6e9e3b"
features = ["chrono-tz", "compute_take", "compute_cast", "compute_aggregate", "compute_if_then_else", "compute_sort", "compute_filter", "compute_temporal", "compute_comparison", "compute_arithmetics", "compute_concatenate", "io_ipc"]

[dependencies.bincode]
version = "1.3.3"

[dependencies.log]
features = [ "std",]
version = "0.4.19"

[dependencies.pyo3]
features = [ "extension-module", "multiple-pymethods", "abi3-py38",]
version = "0.19.2"
optional = true

[dependencies.pyo3-log]
version = "0.8.3"
optional = true

[dependencies.serde]
features = [ "derive", "rc","rc",]
version = "1.0.200"
