[dependencies]
common-error = {path = "../common-error", default-features = false}
csv-async = "1.3.0"
daft-compression = {path = "../daft-compression", default-features = false}
daft-core = {path = "../daft-core", default-features = false}
daft-decoding = {path = "../daft-decoding" }
daft-dsl = {path = "../daft-dsl", default-features = false}
daft-io = {path = "../daft-io", default-features = false}
daft-table = {path = "../daft-table", default-features = false}
lexical-core = {version = "0.8"}
simdutf8 = "0.1.3"
async-compat = "0.2.3"
async-stream = "0.3.5"
bytes = "1.6.0"
chrono = "0.4.26"
chrono-tz = "0.8.4"
futures = "0.3.30"
rayon = "1.10.0"
tokio-util = "0.7.11"
url = "2.4.0"

[features]
default = ["python"]
python = ["dep:pyo3", "dep:pyo3-log", "common-error/python", "daft-core/python", "daft-io/python", "daft-table/python", "daft-dsl/python"]

[package]
edition = "2021"
name = "daft-csv"
version = "0.2.26"

[dependencies.async-compression]
version = "0.4.10"
features = [ "tokio", "all-algorithms",]

[dependencies.snafu]
version = "0.7.4"
features = [ "futures",]

[dependencies.tokio]
version = "1.37.0"
features = [ "net", "time", "bytes", "process", "signal", "macros", "rt", "rt-multi-thread",]

[dependencies.tokio-stream]
version = "0.1.14"
features = [ "fs",]

[dependencies.arrow2]
git = "https://github.com/Eventual-Inc/arrow2"
package = "arrow2"
rev = "4a893a1d05e643273c984c6ccc21f4904d6e9e3b"
features = ["io_csv", "io_csv_async"]

[dependencies.bincode]
version = "1.3.3"

[dependencies.log]
features = [ "std",]
version = "0.4.19"

[dependencies.pyo3]
features = [ "extension-module", "multiple-pymethods", "abi3-py38",]
version = "0.19.2"
optional = true

[dependencies.pyo3-log]
version = "0.8.3"
optional = true

[dependencies.serde]
features = [ "derive", "rc",]
version = "1.0.200"
