[tool.poetry]
name = "dcs-scripts"
version = "1.2.0"
description = "Helper scripts for Draycon Cell Segmentation (dcs) workflows"
authors = ["Arun Nemani <neman014@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
requests = "^2.25.1"
azure-identity = "^1.16.0"
azure-batch = "^14.2.0"
azure-keyvault-secrets = "^4.8.0"
azure-storage-blob = "^12.20.0"
pyyaml = "^6.0.1"
pandas = "<2.0"
matplotlib = "<3.9"
seaborn = "<0.12"
statannotations = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"

[tool.poetry.scripts]
dcs = "dcs_scripts.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
