[tool.poetry]
name = "AndroStats"
version = "0.1.9"
description = "Stats for andrology"
authors = ["M-Jeffryes <michael@maleboxhealth.com>"]
readme = "README.md"
packages = [{include = "AndroStats"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.4"
matplotlib = "^3.9.0"
seaborn = "^0.13.2"


[tool.poetry.group.dev.dependencies]
twine = "^5.1.0"
versioneer = "^0.29"

[tool.poe.tasks]
lint = "black --check ."
lint-fix = "black ."
type-check = "mypy MbhModelling tests --strict"
test = "pytest"

[tool.black]
line-length = 180

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
