# ******************************************************************************
#
# django-loader, a configuration and secret loader for Django
#
# Copyright 2021-2024 Jeremy A Gray <gray@flyquackswim.com>.
#
# SPDX-License-Identifier: MIT
#
# ******************************************************************************

[build-system]

# Poetry.
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool]

[tool.bandit]

exclude_dirs = [
  ".git",
  ".pytest_cache",
  ".tox",
  ".venv",
  "build",
  "dist",
  "htmlcov",
  "django_loader.egg-info",
  "htmlcov",
]

[tool.bandit.assert_used]

skips = [
  "**/test_*.py",
]

[tool.black]

line-length = 88
include = "\\.pyi?$"
exclude = '''
(
  /(
    \.git
    | \.pytest_cache
    | __pycache__
    | htmlcov
  )/
)
'''
force_exclude = '.*/migrations/.*'

[tool.coverage.run]

omit = ["*migrations*"]

[tool.isort]

ensure_newline_before_comments = true
force_single_line = true
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
skip = "migrations"

[tool.pccc]

header_length = 50
body_length = 72
rewrap = false
spell_check = false
repair = false

types = [
  "depends",
  "doc",
  "feat",
  "fix",
  "perf",
  "refactor",
  "release",
  "style",
  "test",
]

scopes = [
  "loader",
  "fake",
  "tooling",
]

footers = [
  "github-closes",
  "signed-off-by",
]

required_footers = [
  "signed-off-by",
]

[tool.poetry]

authors = ["Jeremy A Gray <gray@flyquackswim.com>"]
description = "a configuration and secret loader for Django"
name = "django-loader"
version = "0.0.14"
license = "MIT"
maintainers = ["Jeremy A Gray <gray@flyquackswim.com>"]
readme = "README.rst"
homepage = "https://github.com/jeremyagray/django-loader"
repository = "https://github.com/jeremyagray/django-loader"

classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Framework :: Django :: 5.0",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Internet :: WWW/HTTP :: Site Management",
]

packages = [
  { include = "loader" },
]

[tool.poetry.dependencies]

Django = ">=5.0,<5.1"
bespon = ">=0"
python = ">=3.10.1,<4.0"
"ruamel.yaml" = ">=0"
toml = ">=0"

[tool.poetry.group.dev.dependencies]

hypothesis = ">=6"
pccc = ">=0"
pre-commit = ">=3"
pyfakefs = ">=5"
pytest = ">=8"
pytest-django = ">=4"
tox = ">=4"

[tool.poetry.scripts]

django-loader = "loader:main"

[tool.poetry.urls]

"Issues" = "https://github.com/jeremyagray/django-loader/issues"
"Documentation" = "https://django-loader.readthedocs.io/"
"Repository" = "https://github.com/jeremyagray/django-loader"

[tool.pytest.ini_options]

DJANGO_SETTINGS_MODULE = "fake.settings"
