[dependencies]
regex = "1.10.4"
serde_json = "1.0.116"

[features]
default = ["python"]
python = ["dep:pyo3"]

[package]
edition = "2021"
name = "common-error"
version = "0.2.26"

[dependencies.arrow2]
git = "https://github.com/Eventual-Inc/arrow2"
package = "arrow2"
rev = "4a893a1d05e643273c984c6ccc21f4904d6e9e3b"

[dependencies.pyo3]
features = [ "extension-module", "multiple-pymethods", "abi3-py38",]
version = "0.19.2"
optional = true
