[dependencies]
common-error = {path = "../common-error", default-features = false}
daft-core = {path = "../daft-core", default-features = false}
daft-csv = {path = "../daft-csv", default-features = false}
daft-dsl = {path = "../daft-dsl", default-features = false}
daft-io = {path = "../daft-io", default-features = false}
daft-json = {path = "../daft-json", default-features = false}
daft-parquet = {path = "../daft-parquet", default-features = false}
daft-scan = {path = "../daft-scan", default-features = false}
daft-stats = {path = "../daft-stats", default-features = false}
daft-table = {path = "../daft-table", default-features = false}
indexmap = { version = "2.1.0", features = ["serde"] }

[features]
default = ["python"]
python = ["dep:pyo3", "common-error/python", "daft-core/python", "daft-dsl/python", "daft-table/python", "daft-io/python", "daft-parquet/python", "daft-scan/python", "daft-stats/python"]

[package]
edition = "2021"
name = "daft-micropartition"
version = "0.2.26"

[dependencies.snafu]
version = "0.7.4"
features = [ "futures",]

[dependencies.tokio]
version = "1.37.0"
features = [ "net", "time", "bytes", "process", "signal", "macros", "rt", "rt-multi-thread",]

[dependencies.arrow2]
git = "https://github.com/Eventual-Inc/arrow2"
package = "arrow2"
rev = "4a893a1d05e643273c984c6ccc21f4904d6e9e3b"

[dependencies.bincode]
version = "1.3.3"

[dependencies.log]
features = [ "std",]
version = "0.4.19"

[dependencies.parquet2]
features = [ "async",]
git = "https://github.com/Eventual-Inc/parquet2"
package = "parquet2"
rev = "d4c24086c4cc824fbabef093ab2fda95d3aacb78"

[dependencies.pyo3]
features = [ "extension-module", "multiple-pymethods", "abi3-py38",]
version = "0.19.2"
optional = true

[dependencies.pyo3-log]
version = "0.8.3"

[dependencies.serde]
features = [ "derive", "rc",]
version = "1.0.200"
