[features]
default = [ "python",]
python = [ "dep:pyo3", "dep:pyo3-log", "daft-core/python", "daft-table/python", "daft-dsl/python", "daft-io/python", "daft-plan/python", "daft-parquet/python", "daft-csv/python", "daft-json/python", "daft-micropartition/python", "daft-scan/python", "daft-stats/python", "common-daft-config/python", "common-system-info/python",]

[lib]
crate-type = [ "cdylib",]
name = "daft"

[package]
edition = "2021"
name = "daft"
publish = false
version = "0.2.26"

[workspace]
members = ["local_dependencies/daft-core", "local_dependencies/daft-io", "local_dependencies/daft-parquet", "local_dependencies/daft-csv", "local_dependencies/daft-json", "local_dependencies/daft-dsl", "local_dependencies/daft-table", "local_dependencies/daft-plan", "local_dependencies/daft-micropartition", "local_dependencies/daft-scan", "local_dependencies/daft-sketch"]

[dependencies.common-daft-config]
path = "local_dependencies/common-daft-config"
default-features = false

[dependencies.common-system-info]
path = "local_dependencies/common-system-info"
default-features = false

[dependencies.daft-compression]
path = "local_dependencies/daft-compression"
default-features = false

[dependencies.daft-core]
path = "local_dependencies/daft-core"
default-features = false

[dependencies.daft-csv]
path = "local_dependencies/daft-csv"
default-features = false

[dependencies.daft-dsl]
path = "local_dependencies/daft-dsl"
default-features = false

[dependencies.daft-io]
path = "local_dependencies/daft-io"
default-features = false

[dependencies.daft-json]
path = "local_dependencies/daft-json"
default-features = false

[dependencies.daft-micropartition]
path = "local_dependencies/daft-micropartition"
default-features = false

[dependencies.daft-parquet]
path = "local_dependencies/daft-parquet"
default-features = false

[dependencies.daft-plan]
path = "local_dependencies/daft-plan"
default-features = false

[dependencies.daft-scan]
path = "local_dependencies/daft-scan"
default-features = false

[dependencies.daft-stats]
path = "local_dependencies/daft-stats"
default-features = false

[dependencies.daft-table]
path = "local_dependencies/daft-table"
default-features = false

[dependencies.lzma-sys]
version = "*"
features = [ "static",]

[profile.dev]
overflow-checks = false

[profile.dev-bench]
codegen-units = 16
debug = 1
inherits = "release"
lto = "thin"
strip = "none"

[profile.release-lto]
codegen-units = 1
inherits = "release"
lto = "fat"

[profile.rust-analyzer]
inherits = "dev"

[workspace.dependencies]
async-compat = "0.2.3"
async-stream = "0.3.5"
bytes = "1.6.0"
chrono = "0.4.26"
chrono-tz = "0.8.4"
comfy-table = "7.1.1"
futures = "0.3.30"
html-escape = "0.2.13"
indexmap = "2.1.0"
itertools = "0.11"
jaq-core = "1.2.0"
jaq-interpret = "1.2.0"
jaq-parse = "1.0.0"
jaq-std = "1.2.0"
num-derive = "0.3.3"
num-traits = "0.2"
rand = "^0.8"
rayon = "1.10.0"
regex = "1.10.4"
rstest = "0.18.2"
serde_json = "1.0.116"
tokio-util = "0.7.11"
url = "2.4.0"

[workspace.package]
edition = "2021"
version = "0.2.26"

[patch.crates-io.arrow2]
git = "https://github.com/Eventual-Inc/arrow2"
rev = "4a893a1d05e643273c984c6ccc21f4904d6e9e3b"

[patch.crates-io.parquet2]
git = "https://github.com/Eventual-Inc/parquet2"
rev = "d4c24086c4cc824fbabef093ab2fda95d3aacb78"

[workspace.dependencies.async-compression]
version = "0.4.10"
features = [ "tokio", "all-algorithms",]

[workspace.dependencies.sketches-ddsketch]
version = "0.2.2"
features = [ "use_serde",]

[workspace.dependencies.snafu]
version = "0.7.4"
features = [ "futures",]

[workspace.dependencies.tokio]
version = "1.37.0"
features = [ "net", "time", "bytes", "process", "signal", "macros", "rt", "rt-multi-thread",]

[workspace.dependencies.tokio-stream]
version = "0.1.14"
features = [ "fs",]

[workspace.dependencies.arrow2]
git = "https://github.com/Eventual-Inc/arrow2"
package = "arrow2"
rev = "4a893a1d05e643273c984c6ccc21f4904d6e9e3b"

[workspace.dependencies.bincode]
version = "1.3.3"

[workspace.dependencies.lazy_static]
version = "1.4.0"

[dependencies.lazy_static]
version = "1.4.0"

[workspace.dependencies.log]
features = [ "std",]
version = "0.4.19"

[workspace.dependencies.parquet2]
features = [ "async",]
git = "https://github.com/Eventual-Inc/parquet2"
package = "parquet2"
rev = "d4c24086c4cc824fbabef093ab2fda95d3aacb78"

[workspace.dependencies.pyo3]
features = [ "extension-module", "multiple-pymethods", "abi3-py38",]
version = "0.19.2"

[dependencies.pyo3]
features = [ "extension-module", "multiple-pymethods", "abi3-py38",]
version = "0.19.2"
optional = true

[workspace.dependencies.pyo3-log]
version = "0.8.3"

[dependencies.pyo3-log]
version = "0.8.3"
optional = true

[workspace.dependencies.serde]
features = [ "derive", "rc",]
version = "1.0.200"

[target."cfg(not(target_env = \"msvc\"))".dependencies.libc]
version = "^0.2.150"
default-features = false

[target."cfg(not(target_env = \"msvc\"))".dependencies.tikv-jemallocator]
version = "0.5.4"
features = [ "disable_initial_exec_tls",]
