[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cell-flower"
version = "1.0.0"
authors = [
  { name="Josef Hoppe", email="hoppe@cs.rwth-aachen.de" },
]
description = "Cell FLOWer processes edge flows using cell complexes."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  'scikit-learn >= 1.2.0',
  'numpy >= 1.20.0',
  'scipy >= 1.10.0'
]

[project.optional-dependencies]
test = [
  'pandas',
  'pytest-cov',
  'networkx'
]

[project.urls]
"Homepage" = "https://github.com/josefhoppe/cell-flower"
"Bug Tracker" = "https://github.com/josefhoppe/cell-flower/issues"

[tool.hatch.build]
exclude = ["examples", "readme_src"]

[tool.pytest.ini_options]
addopts = "-ra --cov --cov-report html --cov-report term-missing --cov-fail-under 75"
testpaths = [
    "tests",
    "tests/cell_flower"
]
pythonpath = ["src"]

[tool.coverage.run]
source = ["src"]