[tool.poetry]
name = "eintorch"
version = "0.2.4"
description = "An alternative interface for torchdim"
authors = ["Jakub Bachurski <kbachurski@gmail.com>", "Euan Ong <euan.l.y.ong@gmail.com>"]
readme = "README.md"
packages = [{include = "eintorch", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.0.0"
expecttest = ">=0.2.1"
setuptools = ">=69.0.3"
ipython = ">=8.0"
black = ">=24.1.1"
prettyprinter = ">=0.18.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.ruff]
ignore = ["E501", "E741"]

[tool.mypy]
check_untyped_defs = true
