[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "polite-lib"
version = "0.0.9.2"
description = ""
authors = ["Alix <me@politeauthority.io>"]
readme = "README.md"
packages = [{ include = "src/polite_lib" }]

[tool.poetry.dependencies]
python = "^3.8.0"
arrow = "1.3.0"
flake8 = "7.0.0"
b2sdk = "2.2.1"
glom = "23.5.0"
minio = "7.2.7"
requests = "2.31.0"
rich = "13.7.1"

[project.urls]
Homepage = "https://github.com/politeauthority/polite-lib"
Issues = "https://github.com/politeauthority/polite-lib/issues"
