[tool.poetry]
name = "ifedit"
version = "0.0.1"
description = "A utility to manage contents of ifupdown configuration files."
license = "MIT"
authors = ["Fedor Zhukov <azryve@gmain.com>"]
repository = "https://github.com/azryve/ifedit"
readme = ["README.md", "LICENSE"]
keywords = ["ifedit", "ifupdown", "network", "configuration"]

[tool.poetry.dependencies]
python = ">=3.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
ruff = "^0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ifedit = "ifedit:main"

[tool.ruff]
exclude = [
    "tests/",
]
