[tool.poetry]
name = "pyxo"
version = "1.2.0"
description = ""
authors = ["ouhammmourachid <rachidouhammou21@gmail.com>"]
repository = "https://github.com/ouhammmourachid/pyxo"
license = "MIT"
readme = "README.md"

[bumpver]
current_version = "1.2.0"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"$',
]

"pyxo/__init__.py" = [
    "^__version__ = '{version}'$",
]

"README.md" = [
    "v{version}$"
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
pyxo = "pyxo.__main__:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
