[tool.poetry]
name = "dataframe_decorators"
version = "0.1.0"
description = "Decorators for pipeline functions involving dataframes"
authors = ["Patrick Bray"]
readme = "README.md"
packages = [{include = "dataframe_decorators"}]

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.7.0"

[tool.poetry.group.dev.dependencies]
coverage = "^7.2.7"
black = {extras = ["jupyter"], version = "^23.3.0"}
flake8 = "^6.0.0"
ipykernel = "^6.23.2"
pytest = "^7.3.2"
isort = "^5.12.0"
beavis = "^0.3.0"
ghp-import = "^2.1.0"
pdoc = "^13.1.1"
invoke = "^2.1.3"
jupyter = {extras = ["black"], version = "^1.0.0"}
pytest-regressions = "^2.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[flake8]
max-line-length = 120
max-complexity = 10
