[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Dockme"
version = "0.2.1"
authors = [
  { name="Jean-Luc Morgenstern", email="mintjonn1410@gmail.com" },
]
description = "Dockme in version 0.2.1"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/LetsJonnTV/Dockmy"
"Bug Tracker" = "https://github.com/LetsJonnTV/Dockmy"